Tamga_Test_WebApp/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tamga_Test_WebApp.Data;
using Tamga_Test_WebApp.Models;

namespace Tamga_Test_WebApp.Controllers
{
    [Authorize(Roles ="admin")]

    public class CompaniesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompaniesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Companies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Companies.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.CompanyId == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompanyId,Name,Address,Phone")] Company company)
        {
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompanyId,Name,Address,Phone")] Company company)
        {
            if (id != company.CompanyId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.CompanyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Companies
                .FirstOrDefaultAsync(m => m.CompanyId == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Companies.FindAsync(id);
            _context.Companies.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _context.Companies.Any(e => e.CompanyId == id);
        }
    }
}

Tamga_Test_WebApp/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tamga_Test_WebApp.Data;
using Tamga_Test_WebApp.Models;

namespace Tamga_Test_WebApp.Controllers
{
    [Authorize]
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmployeesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            ViewBag.Applicants = new SelectList(_context.Applicants, "ApplicantId", "Name");
            // var applicationDbContext = _context.Employees.Include(e => e.Applicant).Include(e => e.Company);
            // return View(await applicationDbContext.ToListAsync());
            var applicants = await _context.Applicants.ToListAsync();
            return View(applicants);
        }

        public async Task<IActionResult> Employeed()
        {
            return View(await _context.Employees.Include(x => x.Applicant).Include(x => x.Position).ToListAsync());
        }


        [HttpPost]
        public async Task<IActionResult> Employ(int applicantId, int positionId)
        {
            if (!ApplicantExists(applicantId))
            {
                return NotFound("Applicant not found");
            }
            if (!PositionExists(positionId))
            {
                return NotFound("Position not found");
            }
            var applicant = await _context.Applicants.FirstOrDefaultAsync(x => x.ApplicantId == applicantId);
            var position = await _context.Positions.FirstOrDefaultAsync(x => x.PositionId == positionId);
            if (applicant.PretendedSalary > position.SalaryForkMax || applicant.PretendedSalary < position.SalaryForkMin)
            {
                return BadRequest("Applicant pretended salary not allowed");
            }
            if (_context.Employees.Any(x => x.PositionId == positionId && x.ApplicantId == applicantId))
            {
                return BadRequest("Applicant already emloyeed");
            }
            _context.Employees.Add(new Employee() { ApplicantId = applicantId, PositionId = positionId });
            await _context.SaveChangesAsync();
            return Json("Трудоустроен");
        }

        private bool PositionExists(int id)
        {
            return _context.Positions.Any(e => e.PositionId == id);
        }
        private bool ApplicantExists(int id)
        {
            return _context.Applicants.Any(e => e.ApplicantId == id);
        }


        /// <summary>
        /// Get positions from db where pretendet salary between salary fork min and max
        /// </summary>
        /// <param name="salary"></param>
        /// <returns>Json array(positions)</returns>
        [HttpGet]
        public async Task<IActionResult> GetPositionsBySalary(int salary)
        {
            var positions = await _context.Positions
                                         .Where(x => x.SalaryForkMin <= salary && x.SalaryForkMax >= salary)
                                         //.Include(x => x.Company)
                                         .ToListAsync();
            return Json(positions);
        }


        /// <summary>
        /// Get positions from db where pretendet salary between salary fork min and max
        /// </summary>
        /// <param name="salary"></param>
        /// <returns>Json array(positions)</returns>

        [HttpGet]
        public async Task<IActionResult> GetApplicantById(int id)
        {
            if (ApplicantExists(id))
            {
                var applicant = await _context.Applicants.Include(x => x.Position).Include(x => x.Employees).FirstOrDefaultAsync(x => x.ApplicantId == id);
                var res = new
                {
                    applicant.ApplicantId,
                    applicant.Age,
                    applicant.LastName,
                    applicant.Name,
                    applicant.Phone,
                    isEmployed = applicant.Employees.Any(),
                    applicant.PretendedSalary,
                    position = applicant.Position?.Name
                };
                return Json(res);
            }
            return NotFound();
        }



        //// GET: Employees/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var employee = await _context.Employees
        //        .Include(e => e.Applicant)
        //        .Include(e => e.Company)
        //        .FirstOrDefaultAsync(m => m.ApplicantId == id);
        //    if (employee == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(employee);
        //}




        //// GET: Employees/Create
        //public IActionResult Create()
        //{
        //    ViewData["ApplicantId"] = new SelectList(_context.Applicants, "ApplicantId", "LastName");
        //    ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address");
        //    return View();
        //}

        //// POST: Employees/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("CompanyId,ApplicantId")] Employee employee)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(employee);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["ApplicantId"] = new SelectList(_context.Applicants, "ApplicantId", "LastName", employee.ApplicantId);
        //    ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address", employee.CompanyId);
        //    return View(employee);
        //}

        //// GET: Employees/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var employee = await _context.Employees.FindAsync(id);
        //    if (employee == null)
        //    {
        //        return NotFound();
        //    }
        //    ViewData["ApplicantId"] = new SelectList(_context.Applicants, "ApplicantId", "LastName", employee.ApplicantId);
        //    ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address", employee.CompanyId);
        //    return View(employee);
        //}

        //// POST: Employees/Edit/5
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("CompanyId,ApplicantId")] Employee employee)
        //{
        //    if (id != employee.ApplicantId)
        //    {
        //        return NotFound();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(employee);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!EmployeeExists(employee.ApplicantId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["ApplicantId"] = new SelectList(_context.Applicants, "ApplicantId", "LastName", employee.ApplicantId);
        //    ViewData["CompanyId"] = new SelectList(_context.Companies, "CompanyId", "Address", employee.CompanyId);
        //    return View(employee);
        //}

        //// GET: Employees/Delete/5
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var employee = await _context.Employees
        //        .Include(e => e.Applicant)
        //        .Include(e => e.Company)
        //        .FirstOrDefaultAsync(m => m.ApplicantId == id);
        //    if (employee == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(employee);
        //}

        //// POST: Employees/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> DeleteConfirmed(int id)
        //{
        //    var employee = await _context.Employees.FindAsync(id);
        //    _context.Employees.Remove(employee);
        //    await _context.SaveChangesAsync();
        //    return RedirectToAction(nameof(Index));
        //}

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.ApplicantId == id);
        }
    }
}

Tamga_Test_WebApp/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Tamga_Test_WebApp.ViewModels;

namespace Tamga_Test_WebApp.Controllers
{
    [Authorize(Roles ="superAdmin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<IdentityUser> _userManager;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index(int? page) => View(_roleManager.Roles.Skip(page.HasValue?page.Value*20:0).Take(20));

        public IActionResult Create() => View();


        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(model:name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role.Name == "superAdmin")
            {
                return BadRequest("Группу суперАдмин нельзя удалить");
            }
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());


        public async Task<IActionResult> Edit(string userId)
        {

            IdentityUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.Where(x=>x.Name!="superAdmin").ToList();
                ChangeRolesViewModel model = new ChangeRolesViewModel
                {
                    UserId = user.Id,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            IdentityUser user = await _userManager.FindByIdAsync(userId);

            if (user != null)
            {
                roles.Remove("superAdmin");
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);
                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);
                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

Tamga_Test_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tamga_Test_WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/bootstrap-form-helpers/css/bootstrap-formhelpers.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Tru La La Company</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @*<li><a asp-area="" asp-controller="Roles" asp-action="Index">Управление ролями</a></li>
                    <li><a asp-area="" asp-controller="Applicants" asp-action="Index">Соискатели</a></li>
                    <li><a asp-area="" asp-controller="Companies" asp-action="Index">Компании</a></li>
                    <li><a asp-area="" asp-controller="Positions" asp-action="Index">Позиции</a></li>*@
                    <partial name="_LinksPartial" />

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Tamga_Test_WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @*Mask for inout*@
        <script src="~/lib/bootstrap-form-helpers/js/bootstrap-formhelpers.js"></script>

        @*Notify*@
        <script src="~/lib/bootstrap-notification/bootstrap-notify.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Tamga_Test_WebApp/Views/Shared/_LinksPartial.cshtml
@using Microsoft.AspNetCore.Identity


@inject SignInManager<IdentityUser>    SignInManager


@if (SignInManager.IsSignedIn(User))
{
    <li><a asp-area="" asp-controller="Employees" asp-action="Index">Трудоустройство</a></li>      
    

@if (User.IsInRole("admin"))
    {
        <li><a asp-area="" asp-controller="Applicants" asp-action="Index">Соискатели</a></li>
        <li><a asp-area="" asp-controller="Companies" asp-action="Index">Компании</a></li>
        <li><a asp-area="" asp-controller="Positions" asp-action="Index">Позиции</a></li>
    }

    @if (User.IsInRole("superAdmin"))
    {
        <li><a asp-area="" asp-controller="Roles" asp-action="Index">Управление ролями</a></li>
    }
    
}